name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'Person to greet'

        default: 'World'

        required: true
env:
  REPO_URL: https://github.com/gitoutof/lede.git
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: x86.config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  TZ: Asia/Shanghai



jobs:
  
  greet:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    

    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.ssh }}"


    - name: SSH connection via tmate
      uses: gitoutof/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          

        
        
          
  #  ./tmate2actions.sh

      
